// @generated by scripts/generate-classic-bindings.sh - do not edit by hand.
//
// windows-bindgen a4f9241, from its own bundled Windows metadata.

windows_core::imp::define_interface!(
    IFileSavePicker,
    IFileSavePicker_Vtbl,
    0x3286ffcb_617f_4cc5_af6a_b3fdf29ad145
);
impl windows_core::RuntimeType for IFileSavePicker {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
    const NAME: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::from_slice(b"Windows.Storage.Pickers.IFileSavePicker");
}
impl windows_core::RuntimeName for IFileSavePicker {
    const NAME: &'static str = "Windows.Storage.Pickers.IFileSavePicker";
}
pub trait IFileSavePicker_Impl: windows_core::IUnknownImpl {
    fn SettingsIdentifier(&self) -> windows_core::Result<windows_core::HSTRING>;
    fn SetSettingsIdentifier(&self, value: &windows_core::HSTRING) -> windows_core::Result<()>;
    fn SuggestedStartLocation(&self) -> windows_core::Result<PickerLocationId>;
    fn SetSuggestedStartLocation(&self, value: PickerLocationId) -> windows_core::Result<()>;
    fn CommitButtonText(&self) -> windows_core::Result<windows_core::HSTRING>;
    fn SetCommitButtonText(&self, value: &windows_core::HSTRING) -> windows_core::Result<()>;
    fn FileTypeChoices(
        &self,
    ) -> windows_core::Result<
        windows_collections::IMap<
            windows_core::HSTRING,
            windows_collections::IVector<windows_core::HSTRING>,
        >,
    >;
    fn DefaultFileExtension(&self) -> windows_core::Result<windows_core::HSTRING>;
    fn SetDefaultFileExtension(&self, value: &windows_core::HSTRING) -> windows_core::Result<()>;
    fn SuggestedSaveFile(&self) -> windows_core::Result<StorageFile>;
    fn SetSuggestedSaveFile(
        &self,
        value: windows_core::Ref<StorageFile>,
    ) -> windows_core::Result<()>;
    fn SuggestedFileName(&self) -> windows_core::Result<windows_core::HSTRING>;
    fn SetSuggestedFileName(&self, value: &windows_core::HSTRING) -> windows_core::Result<()>;
    fn PickSaveFileAsync(
        &self,
    ) -> windows_core::Result<windows_future::IAsyncOperation<StorageFile>>;
}
impl IFileSavePicker_Vtbl {
    pub const fn new<Identity: IFileSavePicker_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn SettingsIdentifier<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileSavePicker_Impl::SettingsIdentifier(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn SetSettingsIdentifier<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            value: *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IFileSavePicker_Impl::SetSettingsIdentifier(this, core::mem::transmute(&value))
                    .into()
            }
        }
        unsafe extern "system" fn SuggestedStartLocation<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut PickerLocationId,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileSavePicker_Impl::SuggestedStartLocation(this) {
                    Ok(ok__) => {
                        result__.write(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn SetSuggestedStartLocation<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            value: PickerLocationId,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IFileSavePicker_Impl::SetSuggestedStartLocation(this, value).into()
            }
        }
        unsafe extern "system" fn CommitButtonText<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileSavePicker_Impl::CommitButtonText(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn SetCommitButtonText<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            value: *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IFileSavePicker_Impl::SetCommitButtonText(this, core::mem::transmute(&value)).into()
            }
        }
        unsafe extern "system" fn FileTypeChoices<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileSavePicker_Impl::FileTypeChoices(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn DefaultFileExtension<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileSavePicker_Impl::DefaultFileExtension(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn SetDefaultFileExtension<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            value: *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IFileSavePicker_Impl::SetDefaultFileExtension(this, core::mem::transmute(&value))
                    .into()
            }
        }
        unsafe extern "system" fn SuggestedSaveFile<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileSavePicker_Impl::SuggestedSaveFile(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn SetSuggestedSaveFile<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            value: *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IFileSavePicker_Impl::SetSuggestedSaveFile(this, core::mem::transmute_copy(&value))
                    .into()
            }
        }
        unsafe extern "system" fn SuggestedFileName<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileSavePicker_Impl::SuggestedFileName(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn SetSuggestedFileName<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            value: *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IFileSavePicker_Impl::SetSuggestedFileName(this, core::mem::transmute(&value))
                    .into()
            }
        }
        unsafe extern "system" fn PickSaveFileAsync<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileSavePicker_Impl::PickSaveFileAsync(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<Identity, IFileSavePicker, OFFSET>(),
            SettingsIdentifier: SettingsIdentifier::<Identity, OFFSET>,
            SetSettingsIdentifier: SetSettingsIdentifier::<Identity, OFFSET>,
            SuggestedStartLocation: SuggestedStartLocation::<Identity, OFFSET>,
            SetSuggestedStartLocation: SetSuggestedStartLocation::<Identity, OFFSET>,
            CommitButtonText: CommitButtonText::<Identity, OFFSET>,
            SetCommitButtonText: SetCommitButtonText::<Identity, OFFSET>,
            FileTypeChoices: FileTypeChoices::<Identity, OFFSET>,
            DefaultFileExtension: DefaultFileExtension::<Identity, OFFSET>,
            SetDefaultFileExtension: SetDefaultFileExtension::<Identity, OFFSET>,
            SuggestedSaveFile: SuggestedSaveFile::<Identity, OFFSET>,
            SetSuggestedSaveFile: SetSuggestedSaveFile::<Identity, OFFSET>,
            SuggestedFileName: SuggestedFileName::<Identity, OFFSET>,
            SetSuggestedFileName: SetSuggestedFileName::<Identity, OFFSET>,
            PickSaveFileAsync: PickSaveFileAsync::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IFileSavePicker as windows_core::Interface>::IID
    }
}
#[repr(C)]
pub struct IFileSavePicker_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub SettingsIdentifier: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SetSettingsIdentifier: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SuggestedStartLocation: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut PickerLocationId,
    ) -> windows_core::HRESULT,
    pub SetSuggestedStartLocation: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        PickerLocationId,
    ) -> windows_core::HRESULT,
    pub CommitButtonText: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SetCommitButtonText: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub FileTypeChoices: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub DefaultFileExtension: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SetDefaultFileExtension: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SuggestedSaveFile: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SetSuggestedSaveFile: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SuggestedFileName: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SetSuggestedFileName: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub PickSaveFileAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IOutputStream,
    IOutputStream_Vtbl,
    0x905a0fe6_bc53_11df_8c49_001e4fc686da
);
impl windows_core::RuntimeType for IOutputStream {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
windows_core::imp::interface_hierarchy!(
    IOutputStream,
    windows_core::IUnknown,
    windows_core::IInspectable
);
#[repr(C)]
pub struct IOutputStream_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
}
windows_core::imp::define_interface!(
    IRandomAccessStreamReference,
    IRandomAccessStreamReference_Vtbl,
    0x33ee3134_1dd6_4e3a_8067_d1c162e8642b
);
impl windows_core::RuntimeType for IRandomAccessStreamReference {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
windows_core::imp::interface_hierarchy!(
    IRandomAccessStreamReference,
    windows_core::IUnknown,
    windows_core::IInspectable
);
#[repr(C)]
pub struct IRandomAccessStreamReference_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
}
windows_core::imp::define_interface!(
    IStorageFile,
    IStorageFile_Vtbl,
    0xfa3f6186_4214_428c_a64c_14c9ac7315ea
);
impl windows_core::RuntimeType for IStorageFile {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
windows_core::imp::interface_hierarchy!(
    IStorageFile,
    windows_core::IUnknown,
    windows_core::IInspectable
);
windows_core::imp::required_hierarchy!(IStorageFile, IRandomAccessStreamReference);
#[repr(C)]
pub struct IStorageFile_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
}
windows_core::imp::define_interface!(
    IStorageFileStatics,
    IStorageFileStatics_Vtbl,
    0x5984c710_daf2_43c8_8bb4_a4d3eacfd03f
);
impl windows_core::RuntimeType for IStorageFileStatics {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
    const NAME: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::from_slice(b"Windows.Storage.IStorageFileStatics");
}
impl windows_core::RuntimeName for IStorageFileStatics {
    const NAME: &'static str = "Windows.Storage.IStorageFileStatics";
}
pub trait IStorageFileStatics_Impl: windows_core::IUnknownImpl {
    fn GetFileFromPathAsync(
        &self,
        path: &windows_core::HSTRING,
    ) -> windows_core::Result<windows_future::IAsyncOperation<StorageFile>>;
    fn GetFileFromApplicationUriAsync(
        &self,
        uri: windows_core::Ref<Uri>,
    ) -> windows_core::Result<windows_future::IAsyncOperation<StorageFile>>;
    fn CreateStreamedFileAsync(
        &self,
        displayNameWithExtension: &windows_core::HSTRING,
        dataRequested: windows_core::Ref<StreamedFileDataRequestedHandler>,
        thumbnail: windows_core::Ref<IRandomAccessStreamReference>,
    ) -> windows_core::Result<windows_future::IAsyncOperation<StorageFile>>;
    fn ReplaceWithStreamedFileAsync(
        &self,
        fileToReplace: windows_core::Ref<IStorageFile>,
        dataRequested: windows_core::Ref<StreamedFileDataRequestedHandler>,
        thumbnail: windows_core::Ref<IRandomAccessStreamReference>,
    ) -> windows_core::Result<windows_future::IAsyncOperation<StorageFile>>;
    fn CreateStreamedFileFromUriAsync(
        &self,
        displayNameWithExtension: &windows_core::HSTRING,
        uri: windows_core::Ref<Uri>,
        thumbnail: windows_core::Ref<IRandomAccessStreamReference>,
    ) -> windows_core::Result<windows_future::IAsyncOperation<StorageFile>>;
    fn ReplaceWithStreamedFileFromUriAsync(
        &self,
        fileToReplace: windows_core::Ref<IStorageFile>,
        uri: windows_core::Ref<Uri>,
        thumbnail: windows_core::Ref<IRandomAccessStreamReference>,
    ) -> windows_core::Result<windows_future::IAsyncOperation<StorageFile>>;
}
impl IStorageFileStatics_Vtbl {
    pub const fn new<Identity: IStorageFileStatics_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn GetFileFromPathAsync<
            Identity: IStorageFileStatics_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            path: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IStorageFileStatics_Impl::GetFileFromPathAsync(
                    this,
                    core::mem::transmute(&path),
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn GetFileFromApplicationUriAsync<
            Identity: IStorageFileStatics_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            uri: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IStorageFileStatics_Impl::GetFileFromApplicationUriAsync(
                    this,
                    core::mem::transmute_copy(&uri),
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn CreateStreamedFileAsync<
            Identity: IStorageFileStatics_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            displaynamewithextension: *mut core::ffi::c_void,
            datarequested: *mut core::ffi::c_void,
            thumbnail: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IStorageFileStatics_Impl::CreateStreamedFileAsync(
                    this,
                    core::mem::transmute(&displaynamewithextension),
                    core::mem::transmute_copy(&datarequested),
                    core::mem::transmute_copy(&thumbnail),
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn ReplaceWithStreamedFileAsync<
            Identity: IStorageFileStatics_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            filetoreplace: *mut core::ffi::c_void,
            datarequested: *mut core::ffi::c_void,
            thumbnail: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IStorageFileStatics_Impl::ReplaceWithStreamedFileAsync(
                    this,
                    core::mem::transmute_copy(&filetoreplace),
                    core::mem::transmute_copy(&datarequested),
                    core::mem::transmute_copy(&thumbnail),
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn CreateStreamedFileFromUriAsync<
            Identity: IStorageFileStatics_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            displaynamewithextension: *mut core::ffi::c_void,
            uri: *mut core::ffi::c_void,
            thumbnail: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IStorageFileStatics_Impl::CreateStreamedFileFromUriAsync(
                    this,
                    core::mem::transmute(&displaynamewithextension),
                    core::mem::transmute_copy(&uri),
                    core::mem::transmute_copy(&thumbnail),
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn ReplaceWithStreamedFileFromUriAsync<
            Identity: IStorageFileStatics_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            filetoreplace: *mut core::ffi::c_void,
            uri: *mut core::ffi::c_void,
            thumbnail: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IStorageFileStatics_Impl::ReplaceWithStreamedFileFromUriAsync(
                    this,
                    core::mem::transmute_copy(&filetoreplace),
                    core::mem::transmute_copy(&uri),
                    core::mem::transmute_copy(&thumbnail),
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<Identity, IStorageFileStatics, OFFSET>(),
            GetFileFromPathAsync: GetFileFromPathAsync::<Identity, OFFSET>,
            GetFileFromApplicationUriAsync: GetFileFromApplicationUriAsync::<Identity, OFFSET>,
            CreateStreamedFileAsync: CreateStreamedFileAsync::<Identity, OFFSET>,
            ReplaceWithStreamedFileAsync: ReplaceWithStreamedFileAsync::<Identity, OFFSET>,
            CreateStreamedFileFromUriAsync: CreateStreamedFileFromUriAsync::<Identity, OFFSET>,
            ReplaceWithStreamedFileFromUriAsync: ReplaceWithStreamedFileFromUriAsync::<
                Identity,
                OFFSET,
            >,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IStorageFileStatics as windows_core::Interface>::IID
    }
}
#[repr(C)]
pub struct IStorageFileStatics_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub GetFileFromPathAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub GetFileFromApplicationUriAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub CreateStreamedFileAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub ReplaceWithStreamedFileAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub CreateStreamedFileFromUriAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub ReplaceWithStreamedFileFromUriAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    )
        -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IUriRuntimeClass,
    IUriRuntimeClass_Vtbl,
    0x9e365e57_48b2_4160_956f_c7385120bbfc
);
impl windows_core::RuntimeType for IUriRuntimeClass {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
#[repr(C)]
pub struct IUriRuntimeClass_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
}
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct PickerLocationId(pub i32);
impl PickerLocationId {
    pub const DocumentsLibrary: Self = Self(0);
    pub const ComputerFolder: Self = Self(1);
    pub const Desktop: Self = Self(2);
    pub const Downloads: Self = Self(3);
    pub const HomeGroup: Self = Self(4);
    pub const MusicLibrary: Self = Self(5);
    pub const PicturesLibrary: Self = Self(6);
    pub const VideosLibrary: Self = Self(7);
    pub const Objects3D: Self = Self(8);
    pub const Unspecified: Self = Self(9);
}
impl windows_core::TypeKind for PickerLocationId {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for PickerLocationId {
    const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"enum(Windows.Storage.Pickers.PickerLocationId;i4)",
    );
}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct StorageFile(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    StorageFile,
    windows_core::IUnknown,
    windows_core::IInspectable,
    IStorageFile
);
windows_core::imp::required_hierarchy!(StorageFile, IRandomAccessStreamReference);
impl StorageFile {
    pub fn GetFileFromPathAsync(
        path: &str,
    ) -> windows_core::Result<windows_future::IAsyncOperation<Self>> {
        Self::IStorageFileStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).GetFileFromPathAsync)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(&windows_core::HSTRING::from(path)),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    pub fn GetFileFromApplicationUriAsync<P0>(
        uri: P0,
    ) -> windows_core::Result<windows_future::IAsyncOperation<Self>>
    where
        P0: windows_core::Param<Uri>,
    {
        Self::IStorageFileStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).GetFileFromApplicationUriAsync)(
                windows_core::Interface::as_raw(this),
                uri.param().abi(),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    pub fn CreateStreamedFileAsync<P1, P2>(
        displaynamewithextension: &str,
        datarequested: P1,
        thumbnail: P2,
    ) -> windows_core::Result<windows_future::IAsyncOperation<Self>>
    where
        P1: windows_core::Param<StreamedFileDataRequestedHandler>,
        P2: windows_core::Param<IRandomAccessStreamReference>,
    {
        Self::IStorageFileStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).CreateStreamedFileAsync)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(&windows_core::HSTRING::from(displaynamewithextension)),
                datarequested.param().abi(),
                thumbnail.param().abi(),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    pub fn ReplaceWithStreamedFileAsync<P0, P1, P2>(
        filetoreplace: P0,
        datarequested: P1,
        thumbnail: P2,
    ) -> windows_core::Result<windows_future::IAsyncOperation<Self>>
    where
        P0: windows_core::Param<IStorageFile>,
        P1: windows_core::Param<StreamedFileDataRequestedHandler>,
        P2: windows_core::Param<IRandomAccessStreamReference>,
    {
        Self::IStorageFileStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).ReplaceWithStreamedFileAsync)(
                windows_core::Interface::as_raw(this),
                filetoreplace.param().abi(),
                datarequested.param().abi(),
                thumbnail.param().abi(),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    pub fn CreateStreamedFileFromUriAsync<P1, P2>(
        displaynamewithextension: &str,
        uri: P1,
        thumbnail: P2,
    ) -> windows_core::Result<windows_future::IAsyncOperation<Self>>
    where
        P1: windows_core::Param<Uri>,
        P2: windows_core::Param<IRandomAccessStreamReference>,
    {
        Self::IStorageFileStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).CreateStreamedFileFromUriAsync)(
                windows_core::Interface::as_raw(this),
                core::mem::transmute_copy(&windows_core::HSTRING::from(displaynamewithextension)),
                uri.param().abi(),
                thumbnail.param().abi(),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    pub fn ReplaceWithStreamedFileFromUriAsync<P0, P1, P2>(
        filetoreplace: P0,
        uri: P1,
        thumbnail: P2,
    ) -> windows_core::Result<windows_future::IAsyncOperation<Self>>
    where
        P0: windows_core::Param<IStorageFile>,
        P1: windows_core::Param<Uri>,
        P2: windows_core::Param<IRandomAccessStreamReference>,
    {
        Self::IStorageFileStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).ReplaceWithStreamedFileFromUriAsync)(
                windows_core::Interface::as_raw(this),
                filetoreplace.param().abi(),
                uri.param().abi(),
                thumbnail.param().abi(),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    fn IStorageFileStatics<R, F: FnOnce(&IStorageFileStatics) -> windows_core::Result<R>>(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<StorageFile, IStorageFileStatics> =
            windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
}
impl windows_core::RuntimeType for StorageFile {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IStorageFile>();
}
unsafe impl windows_core::Interface for StorageFile {
    type Vtable = <IStorageFile as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IStorageFile as windows_core::Interface>::IID;
}
impl core::ops::Deref for StorageFile {
    type Target = IStorageFile;
    fn deref(&self) -> &Self::Target {
        unsafe { core::mem::transmute(self) }
    }
}
impl windows_core::RuntimeName for StorageFile {
    const NAME: &'static str = "Windows.Storage.StorageFile";
}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct StreamedFileDataRequest(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    StreamedFileDataRequest,
    windows_core::IUnknown,
    windows_core::IInspectable,
    IOutputStream
);
impl windows_core::RuntimeType for StreamedFileDataRequest {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IOutputStream>();
}
unsafe impl windows_core::Interface for StreamedFileDataRequest {
    type Vtable = <IOutputStream as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IOutputStream as windows_core::Interface>::IID;
}
impl core::ops::Deref for StreamedFileDataRequest {
    type Target = IOutputStream;
    fn deref(&self) -> &Self::Target {
        unsafe { core::mem::transmute(self) }
    }
}
impl windows_core::RuntimeName for StreamedFileDataRequest {
    const NAME: &'static str = "Windows.Storage.StreamedFileDataRequest";
}
windows_core::imp::define_interface!(
    StreamedFileDataRequestedHandler,
    StreamedFileDataRequestedHandler_Vtbl,
    0xfef6a824_2fe1_4d07_a35b_b77c50b5f4cc
);
impl windows_core::RuntimeType for StreamedFileDataRequestedHandler {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
impl StreamedFileDataRequestedHandler {
    pub fn new<F: Fn(windows_core::Ref<StreamedFileDataRequest>) + 'static>(invoke: F) -> Self {
        let com = windows_core::imp::DelegateBox::<Self, F>::new(
            &StreamedFileDataRequestedHandlerBox::<F>::VTABLE,
            invoke,
        );
        unsafe { core::mem::transmute(windows_core::imp::box_new(com)) }
    }
}
#[repr(C)]
pub struct StreamedFileDataRequestedHandler_Vtbl {
    base__: windows_core::IUnknown_Vtbl,
    Invoke: unsafe extern "system" fn(
        this: *mut core::ffi::c_void,
        stream: *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
struct StreamedFileDataRequestedHandlerBox<
    F: Fn(windows_core::Ref<StreamedFileDataRequest>) + 'static,
>(core::marker::PhantomData<(fn() -> F,)>);
impl<F: Fn(windows_core::Ref<StreamedFileDataRequest>) + 'static>
    StreamedFileDataRequestedHandlerBox<F>
{
    const VTABLE : StreamedFileDataRequestedHandler_Vtbl < > = StreamedFileDataRequestedHandler_Vtbl::< > { base__ : windows_core::IUnknown_Vtbl { QueryInterface : windows_core::imp::DelegateBox::< StreamedFileDataRequestedHandler , F >::QueryInterface , AddRef : windows_core::imp::DelegateBox::< StreamedFileDataRequestedHandler , F >::AddRef , Release : windows_core::imp::DelegateBox::< StreamedFileDataRequestedHandler , F >::Release , } , Invoke : Self::Invoke , } ;
    unsafe extern "system" fn Invoke(
        this: *mut core::ffi::c_void,
        stream: *mut core::ffi::c_void,
    ) -> windows_core::HRESULT {
        unsafe {
            let this = &mut *(this as *mut *mut core::ffi::c_void
                as *mut windows_core::imp::DelegateBox<StreamedFileDataRequestedHandler, F>);
            (this.invoke)(core::mem::transmute_copy(&stream));
            windows_core::HRESULT(0)
        }
    }
}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Uri(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(Uri, windows_core::IUnknown, windows_core::IInspectable);
impl windows_core::RuntimeType for Uri {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IUriRuntimeClass>();
}
unsafe impl windows_core::Interface for Uri {
    type Vtable = <IUriRuntimeClass as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IUriRuntimeClass as windows_core::Interface>::IID;
}
impl core::ops::Deref for Uri {
    type Target = IUriRuntimeClass;
    fn deref(&self) -> &Self::Target {
        unsafe { core::mem::transmute(self) }
    }
}
impl windows_core::RuntimeName for Uri {
    const NAME: &'static str = "Windows.Foundation.Uri";
}
unsafe impl Send for Uri {}
unsafe impl Sync for Uri {}
