#!/bin/sh
# Regenerates src/com/pickers/bindings.rs for the classic `Windows.Storage.Pickers` classes.
#
# The `windows` crate already binds these interfaces, but only as raw `*_Vtbl` structs: it emits
# an `_Impl` trait only for interfaces a caller is allowed to implement, and both a picker
# interface and a statics interface are marked as belonging exclusively to their own class. So
# the bindings the crate ships can be called through but not implemented, which is the wrong half
# for a runtime whose whole job is to be the implementation.
#
# Naming those types explicitly in the filter overrides that judgement and produces the `_Impl`
# traits, which is all this script exists to do. The metadata is the one `windows-bindgen`
# already bundles, so nothing is downloaded.
#
# Types that appear in the generated signatures - `StorageFile`, `Uri` and the streamed-file
# handler - come along as local definitions rather than as references to the `windows` crate,
# because the generator has no way to be told that crate already has them. They are the same
# types by ABI and by IID, so a pointer built against one is a pointer against the other; only
# the Rust names differ.
#
# `windows-bindgen` is pinned to the same revision as the `windows-*` crates the DLL builds
# against, because generated code and the core crate it expands into are versioned together.
#
# Run this only to move to a different windows-rs revision; the output is committed, and building
# the DLL does not need this script.

set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

bindgen_rev=a4f9241

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

cat > "$work/Cargo.toml" <<EOF
[package]
name = "generate-classic-bindings"
version = "0.0.0"
edition = "2024"

[dependencies.windows-bindgen]
git = "https://github.com/microsoft/windows-rs"
rev = "$bindgen_rev"
EOF

mkdir -p "$work/src"
cat > "$work/src/main.rs" <<'EOF'
fn main() {
    windows_bindgen::bindgen([
        "--in", "default",
        "--out", "bindings.rs",
        "--filter",
        "Windows.Storage.Pickers.IFileSavePicker",
        "Windows.Storage.IStorageFileStatics",
        "--implement",
        "Windows.Storage.Pickers.IFileSavePicker",
        "Windows.Storage.IStorageFileStatics",
        "--flat",
        "--minimal",
    ]);
}
EOF

# Built for the host, not the DLL's target: this is a code generator, not part of the runtime.
(cd "$work" && cargo run --release --target x86_64-unknown-linux-gnu)

out=$root/src/com/pickers/bindings.rs

# Stamp the provenance into the file itself, so anyone who opens it knows not to edit it and
# knows what would have to change to make it different. `@generated` is the marker review tools
# and `.gitattributes` look for.
{
    echo "// @generated by scripts/generate-classic-bindings.sh - do not edit by hand."
    echo "//"
    echo "// windows-bindgen $bindgen_rev, from its own bundled Windows metadata."
    echo
    cat "$work/bindings.rs"
} > "$out"

echo
echo "wrote $out"
