#!/bin/sh
# Regenerates src/com/pickers/appsdk/bindings.rs from the Windows App SDK's published metadata.
#
# The App SDK pickers are a different class family from the ones in `Windows.Storage.Pickers`:
# a different namespace, different interfaces, and IIDs that MIDL derives from whole type
# signatures rather than from names, so they cannot be worked out by hand. The metadata that
# defines them ships in the `Microsoft.WindowsAppSDK.Foundation` NuGet package, which is where
# this gets them. `Microsoft.UI.winmd`, from the InteractiveExperiences package, comes along for
# the `WindowId` a picker is constructed with.
#
# `windows-bindgen` is pinned to the same revision as the `windows-*` crates the DLL builds
# against, because generated code and the core crate it expands into are versioned together.
#
# Run this only to move to a different App SDK version; the output is committed, and building
# the DLL does not need the network or this script.

set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

# The version the title in question ships. Its picker factory IID has to match the metadata's,
# or the class is answered with the wrong vtable - see the module docs in appsdk/mod.rs.
foundation_version=1.8.260709000
experiences_version=1.8.260708001
bindgen_rev=a4f9241

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
mkdir -p "$work/winmd"

fetch() {
    url="https://api.nuget.org/v3-flatcontainer/$1/$2/$1.$2.nupkg"
    echo ">>> $1 $2"
    curl -sSf --max-time 300 -o "$work/$1.nupkg" "$url"
}

fetch microsoft.windowsappsdk.foundation "$foundation_version"
fetch microsoft.windowsappsdk.interactiveexperiences "$experiences_version"

python3 - "$work" <<'PY'
import sys, zipfile
work = sys.argv[1]
wanted = ("microsoft.windows.storage.pickers.winmd", "microsoft.ui.winmd")
for package in ("microsoft.windowsappsdk.foundation", "microsoft.windowsappsdk.interactiveexperiences"):
    archive = zipfile.ZipFile(f"{work}/{package}.nupkg")
    for name in archive.namelist():
        leaf = name.split("/")[-1]
        if leaf.lower() in wanted:
            open(f"{work}/winmd/{leaf}", "wb").write(archive.read(name))
            print("extracted", leaf)
PY

cat > "$work/Cargo.toml" <<EOF
[package]
name = "generate-appsdk-bindings"
version = "0.0.0"
edition = "2024"

[dependencies.windows-bindgen]
git = "https://github.com/microsoft/windows-rs"
rev = "$bindgen_rev"
EOF

mkdir -p "$work/src"
cat > "$work/src/main.rs" <<'EOF'
fn main() {
    windows_bindgen::bindgen([
        "--in", "winmd/Microsoft.Windows.Storage.Pickers.winmd",
        "--in", "winmd/Microsoft.UI.winmd",
        "--in", "default",
        "--out", "bindings.rs",
        "--filter", "Microsoft.Windows.Storage.Pickers", "Microsoft.UI.WindowId",
        "--implement",
        "--flat",
    ]);
}
EOF

# Built for the host, not the DLL's target: this is a code generator, not part of the runtime.
(cd "$work" && cargo run --release --target x86_64-unknown-linux-gnu)

out=$root/src/com/pickers/appsdk/bindings.rs

# Stamp the provenance into the file itself, so anyone who opens it knows not to edit it and
# knows what would have to change to make it different. `@generated` is the marker review tools
# and `.gitattributes` look for.
{
    echo "// @generated by scripts/generate-appsdk-bindings.sh - do not edit by hand."
    echo "//"
    echo "// Microsoft.WindowsAppSDK.Foundation $foundation_version, Microsoft.WindowsAppSDK.InteractiveExperiences $experiences_version, windows-bindgen $bindgen_rev."
    echo
    cat "$work/bindings.rs"
} > "$out"
echo
echo "wrote $out"
