// @generated by scripts/generate-appsdk-bindings.sh - do not edit by hand.
//
// Microsoft.WindowsAppSDK.Foundation 1.8.260709000, Microsoft.WindowsAppSDK.InteractiveExperiences 1.8.260708001, windows-bindgen a4f9241.

#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct FileOpenPicker(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    FileOpenPicker,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl FileOpenPicker {
    pub fn ViewMode(&self) -> windows_core::Result<PickerViewMode> {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).ViewMode)(
                windows_core::Interface::as_raw(self),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetViewMode(&self, value: PickerViewMode) -> windows_core::Result<()> {
        unsafe {
            (windows_core::Interface::vtable(self).SetViewMode)(
                windows_core::Interface::as_raw(self),
                value,
            )
            .ok()
        }
    }
    pub fn SuggestedStartLocation(&self) -> windows_core::Result<PickerLocationId> {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).SuggestedStartLocation)(
                windows_core::Interface::as_raw(self),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetSuggestedStartLocation(&self, value: PickerLocationId) -> windows_core::Result<()> {
        unsafe {
            (windows_core::Interface::vtable(self).SetSuggestedStartLocation)(
                windows_core::Interface::as_raw(self),
                value,
            )
            .ok()
        }
    }
    pub fn CommitButtonText(&self) -> windows_core::Result<windows_core::HSTRING> {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).CommitButtonText)(
                windows_core::Interface::as_raw(self),
                &mut result__,
            )
            .map(|| core::mem::transmute(result__))
        }
    }
    pub fn SetCommitButtonText(&self, value: &windows_core::HSTRING) -> windows_core::Result<()> {
        unsafe {
            (windows_core::Interface::vtable(self).SetCommitButtonText)(
                windows_core::Interface::as_raw(self),
                core::mem::transmute_copy(value),
            )
            .ok()
        }
    }
    pub fn FileTypeFilter(
        &self,
    ) -> windows_core::Result<windows_collections::IVector<windows_core::HSTRING>> {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).FileTypeFilter)(
                windows_core::Interface::as_raw(self),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn PickSingleFileAsync(
        &self,
    ) -> windows_core::Result<windows_future::IAsyncOperation<PickFileResult>> {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).PickSingleFileAsync)(
                windows_core::Interface::as_raw(self),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn PickMultipleFilesAsync(
        &self,
    ) -> windows_core::Result<
        windows_future::IAsyncOperation<windows_collections::IVectorView<PickFileResult>>,
    > {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).PickMultipleFilesAsync)(
                windows_core::Interface::as_raw(self),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn CreateInstance(windowid: WindowId) -> windows_core::Result<Self> {
        Self::IFileOpenPickerFactory(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).CreateInstance)(
                windows_core::Interface::as_raw(this),
                windowid,
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    fn IFileOpenPickerFactory<R, F: FnOnce(&IFileOpenPickerFactory) -> windows_core::Result<R>>(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<FileOpenPicker, IFileOpenPickerFactory> =
            windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
}
impl windows_core::RuntimeType for FileOpenPicker {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IFileOpenPicker>();
}
unsafe impl windows_core::Interface for FileOpenPicker {
    type Vtable = <IFileOpenPicker as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IFileOpenPicker as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for FileOpenPicker {
    const NAME: &'static str = "Microsoft.Windows.Storage.Pickers.FileOpenPicker";
}
unsafe impl Send for FileOpenPicker {}
unsafe impl Sync for FileOpenPicker {}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct FileSavePicker(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    FileSavePicker,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl FileSavePicker {
    pub fn SuggestedStartLocation(&self) -> windows_core::Result<PickerLocationId> {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).SuggestedStartLocation)(
                windows_core::Interface::as_raw(self),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetSuggestedStartLocation(&self, value: PickerLocationId) -> windows_core::Result<()> {
        unsafe {
            (windows_core::Interface::vtable(self).SetSuggestedStartLocation)(
                windows_core::Interface::as_raw(self),
                value,
            )
            .ok()
        }
    }
    pub fn CommitButtonText(&self) -> windows_core::Result<windows_core::HSTRING> {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).CommitButtonText)(
                windows_core::Interface::as_raw(self),
                &mut result__,
            )
            .map(|| core::mem::transmute(result__))
        }
    }
    pub fn SetCommitButtonText(&self, value: &windows_core::HSTRING) -> windows_core::Result<()> {
        unsafe {
            (windows_core::Interface::vtable(self).SetCommitButtonText)(
                windows_core::Interface::as_raw(self),
                core::mem::transmute_copy(value),
            )
            .ok()
        }
    }
    pub fn FileTypeChoices(
        &self,
    ) -> windows_core::Result<
        windows_collections::IMap<
            windows_core::HSTRING,
            windows_collections::IVector<windows_core::HSTRING>,
        >,
    > {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).FileTypeChoices)(
                windows_core::Interface::as_raw(self),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn DefaultFileExtension(&self) -> windows_core::Result<windows_core::HSTRING> {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).DefaultFileExtension)(
                windows_core::Interface::as_raw(self),
                &mut result__,
            )
            .map(|| core::mem::transmute(result__))
        }
    }
    pub fn SetDefaultFileExtension(
        &self,
        value: &windows_core::HSTRING,
    ) -> windows_core::Result<()> {
        unsafe {
            (windows_core::Interface::vtable(self).SetDefaultFileExtension)(
                windows_core::Interface::as_raw(self),
                core::mem::transmute_copy(value),
            )
            .ok()
        }
    }
    pub fn SuggestedFileName(&self) -> windows_core::Result<windows_core::HSTRING> {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).SuggestedFileName)(
                windows_core::Interface::as_raw(self),
                &mut result__,
            )
            .map(|| core::mem::transmute(result__))
        }
    }
    pub fn SetSuggestedFileName(&self, value: &windows_core::HSTRING) -> windows_core::Result<()> {
        unsafe {
            (windows_core::Interface::vtable(self).SetSuggestedFileName)(
                windows_core::Interface::as_raw(self),
                core::mem::transmute_copy(value),
            )
            .ok()
        }
    }
    pub fn SuggestedFolder(&self) -> windows_core::Result<windows_core::HSTRING> {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).SuggestedFolder)(
                windows_core::Interface::as_raw(self),
                &mut result__,
            )
            .map(|| core::mem::transmute(result__))
        }
    }
    pub fn SetSuggestedFolder(&self, value: &windows_core::HSTRING) -> windows_core::Result<()> {
        unsafe {
            (windows_core::Interface::vtable(self).SetSuggestedFolder)(
                windows_core::Interface::as_raw(self),
                core::mem::transmute_copy(value),
            )
            .ok()
        }
    }
    pub fn PickSaveFileAsync(
        &self,
    ) -> windows_core::Result<windows_future::IAsyncOperation<PickFileResult>> {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).PickSaveFileAsync)(
                windows_core::Interface::as_raw(self),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn CreateInstance(windowid: WindowId) -> windows_core::Result<Self> {
        Self::IFileSavePickerFactory(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).CreateInstance)(
                windows_core::Interface::as_raw(this),
                windowid,
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    fn IFileSavePickerFactory<R, F: FnOnce(&IFileSavePickerFactory) -> windows_core::Result<R>>(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<FileSavePicker, IFileSavePickerFactory> =
            windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
}
impl windows_core::RuntimeType for FileSavePicker {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IFileSavePicker>();
}
unsafe impl windows_core::Interface for FileSavePicker {
    type Vtable = <IFileSavePicker as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IFileSavePicker as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for FileSavePicker {
    const NAME: &'static str = "Microsoft.Windows.Storage.Pickers.FileSavePicker";
}
unsafe impl Send for FileSavePicker {}
unsafe impl Sync for FileSavePicker {}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct FolderPicker(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    FolderPicker,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl FolderPicker {
    pub fn ViewMode(&self) -> windows_core::Result<PickerViewMode> {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).ViewMode)(
                windows_core::Interface::as_raw(self),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetViewMode(&self, value: PickerViewMode) -> windows_core::Result<()> {
        unsafe {
            (windows_core::Interface::vtable(self).SetViewMode)(
                windows_core::Interface::as_raw(self),
                value,
            )
            .ok()
        }
    }
    pub fn SuggestedStartLocation(&self) -> windows_core::Result<PickerLocationId> {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).SuggestedStartLocation)(
                windows_core::Interface::as_raw(self),
                &mut result__,
            )
            .map(|| result__)
        }
    }
    pub fn SetSuggestedStartLocation(&self, value: PickerLocationId) -> windows_core::Result<()> {
        unsafe {
            (windows_core::Interface::vtable(self).SetSuggestedStartLocation)(
                windows_core::Interface::as_raw(self),
                value,
            )
            .ok()
        }
    }
    pub fn CommitButtonText(&self) -> windows_core::Result<windows_core::HSTRING> {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).CommitButtonText)(
                windows_core::Interface::as_raw(self),
                &mut result__,
            )
            .map(|| core::mem::transmute(result__))
        }
    }
    pub fn SetCommitButtonText(&self, value: &windows_core::HSTRING) -> windows_core::Result<()> {
        unsafe {
            (windows_core::Interface::vtable(self).SetCommitButtonText)(
                windows_core::Interface::as_raw(self),
                core::mem::transmute_copy(value),
            )
            .ok()
        }
    }
    pub fn PickSingleFolderAsync(
        &self,
    ) -> windows_core::Result<windows_future::IAsyncOperation<PickFolderResult>> {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).PickSingleFolderAsync)(
                windows_core::Interface::as_raw(self),
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        }
    }
    pub fn CreateInstance(windowid: WindowId) -> windows_core::Result<Self> {
        Self::IFolderPickerFactory(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).CreateInstance)(
                windows_core::Interface::as_raw(this),
                windowid,
                &mut result__,
            )
            .and_then(|| windows_core::Type::from_abi(result__))
        })
    }
    fn IFolderPickerFactory<R, F: FnOnce(&IFolderPickerFactory) -> windows_core::Result<R>>(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<FolderPicker, IFolderPickerFactory> =
            windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
}
impl windows_core::RuntimeType for FolderPicker {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IFolderPicker>();
}
unsafe impl windows_core::Interface for FolderPicker {
    type Vtable = <IFolderPicker as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IFolderPicker as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for FolderPicker {
    const NAME: &'static str = "Microsoft.Windows.Storage.Pickers.FolderPicker";
}
unsafe impl Send for FolderPicker {}
unsafe impl Sync for FolderPicker {}
windows_core::imp::define_interface!(
    IFileOpenPicker,
    IFileOpenPicker_Vtbl,
    0x9d00f175_c783_51bd_8c93_fb63695d3abc
);
impl windows_core::RuntimeType for IFileOpenPicker {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
    const NAME: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"Microsoft.Windows.Storage.Pickers.IFileOpenPicker",
    );
}
impl windows_core::RuntimeName for IFileOpenPicker {
    const NAME: &'static str = "Microsoft.Windows.Storage.Pickers.IFileOpenPicker";
}
pub trait IFileOpenPicker_Impl: windows_core::IUnknownImpl {
    fn ViewMode(&self) -> windows_core::Result<PickerViewMode>;
    fn SetViewMode(&self, value: PickerViewMode) -> windows_core::Result<()>;
    fn SuggestedStartLocation(&self) -> windows_core::Result<PickerLocationId>;
    fn SetSuggestedStartLocation(&self, value: PickerLocationId) -> windows_core::Result<()>;
    fn CommitButtonText(&self) -> windows_core::Result<windows_core::HSTRING>;
    fn SetCommitButtonText(&self, value: &windows_core::HSTRING) -> windows_core::Result<()>;
    fn FileTypeFilter(
        &self,
    ) -> windows_core::Result<windows_collections::IVector<windows_core::HSTRING>>;
    fn PickSingleFileAsync(
        &self,
    ) -> windows_core::Result<windows_future::IAsyncOperation<PickFileResult>>;
    fn PickMultipleFilesAsync(
        &self,
    ) -> windows_core::Result<
        windows_future::IAsyncOperation<windows_collections::IVectorView<PickFileResult>>,
    >;
}
impl IFileOpenPicker_Vtbl {
    pub const fn new<Identity: IFileOpenPicker_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn ViewMode<Identity: IFileOpenPicker_Impl, const OFFSET: isize>(
            this: *mut core::ffi::c_void,
            result__: *mut PickerViewMode,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileOpenPicker_Impl::ViewMode(this) {
                    Ok(ok__) => {
                        result__.write(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn SetViewMode<
            Identity: IFileOpenPicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            value: PickerViewMode,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IFileOpenPicker_Impl::SetViewMode(this, value).into()
            }
        }
        unsafe extern "system" fn SuggestedStartLocation<
            Identity: IFileOpenPicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut PickerLocationId,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileOpenPicker_Impl::SuggestedStartLocation(this) {
                    Ok(ok__) => {
                        result__.write(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn SetSuggestedStartLocation<
            Identity: IFileOpenPicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            value: PickerLocationId,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IFileOpenPicker_Impl::SetSuggestedStartLocation(this, value).into()
            }
        }
        unsafe extern "system" fn CommitButtonText<
            Identity: IFileOpenPicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileOpenPicker_Impl::CommitButtonText(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn SetCommitButtonText<
            Identity: IFileOpenPicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            value: *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IFileOpenPicker_Impl::SetCommitButtonText(this, core::mem::transmute(&value)).into()
            }
        }
        unsafe extern "system" fn FileTypeFilter<
            Identity: IFileOpenPicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileOpenPicker_Impl::FileTypeFilter(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn PickSingleFileAsync<
            Identity: IFileOpenPicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileOpenPicker_Impl::PickSingleFileAsync(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn PickMultipleFilesAsync<
            Identity: IFileOpenPicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileOpenPicker_Impl::PickMultipleFilesAsync(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<Identity, IFileOpenPicker, OFFSET>(),
            ViewMode: ViewMode::<Identity, OFFSET>,
            SetViewMode: SetViewMode::<Identity, OFFSET>,
            SuggestedStartLocation: SuggestedStartLocation::<Identity, OFFSET>,
            SetSuggestedStartLocation: SetSuggestedStartLocation::<Identity, OFFSET>,
            CommitButtonText: CommitButtonText::<Identity, OFFSET>,
            SetCommitButtonText: SetCommitButtonText::<Identity, OFFSET>,
            FileTypeFilter: FileTypeFilter::<Identity, OFFSET>,
            PickSingleFileAsync: PickSingleFileAsync::<Identity, OFFSET>,
            PickMultipleFilesAsync: PickMultipleFilesAsync::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IFileOpenPicker as windows_core::Interface>::IID
    }
}
#[repr(C)]
pub struct IFileOpenPicker_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub ViewMode: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut PickerViewMode,
    ) -> windows_core::HRESULT,
    pub SetViewMode:
        unsafe extern "system" fn(*mut core::ffi::c_void, PickerViewMode) -> windows_core::HRESULT,
    pub SuggestedStartLocation: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut PickerLocationId,
    ) -> windows_core::HRESULT,
    pub SetSuggestedStartLocation: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        PickerLocationId,
    ) -> windows_core::HRESULT,
    pub CommitButtonText: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SetCommitButtonText: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub FileTypeFilter: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub PickSingleFileAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub PickMultipleFilesAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IFileOpenPickerFactory,
    IFileOpenPickerFactory_Vtbl,
    0x315e86d7_d7a2_5d81_b379_7af78207b1af
);
impl windows_core::RuntimeType for IFileOpenPickerFactory {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
    const NAME: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"Microsoft.Windows.Storage.Pickers.IFileOpenPickerFactory",
    );
}
impl windows_core::RuntimeName for IFileOpenPickerFactory {
    const NAME: &'static str = "Microsoft.Windows.Storage.Pickers.IFileOpenPickerFactory";
}
pub trait IFileOpenPickerFactory_Impl: windows_core::IUnknownImpl {
    fn CreateInstance(&self, windowId: &WindowId) -> windows_core::Result<FileOpenPicker>;
}
impl IFileOpenPickerFactory_Vtbl {
    pub const fn new<Identity: IFileOpenPickerFactory_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn CreateInstance<
            Identity: IFileOpenPickerFactory_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            windowid: WindowId,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileOpenPickerFactory_Impl::CreateInstance(
                    this,
                    core::mem::transmute(&windowid),
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<Identity, IFileOpenPickerFactory, OFFSET>(
            ),
            CreateInstance: CreateInstance::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IFileOpenPickerFactory as windows_core::Interface>::IID
    }
}
#[repr(C)]
pub struct IFileOpenPickerFactory_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub CreateInstance: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        WindowId,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IFileSavePicker,
    IFileSavePicker_Vtbl,
    0x79f1f4df_741b_59b2_aa06_fe9ac817b7dd
);
impl windows_core::RuntimeType for IFileSavePicker {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
    const NAME: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"Microsoft.Windows.Storage.Pickers.IFileSavePicker",
    );
}
impl windows_core::RuntimeName for IFileSavePicker {
    const NAME: &'static str = "Microsoft.Windows.Storage.Pickers.IFileSavePicker";
}
pub trait IFileSavePicker_Impl: windows_core::IUnknownImpl {
    fn SuggestedStartLocation(&self) -> windows_core::Result<PickerLocationId>;
    fn SetSuggestedStartLocation(&self, value: PickerLocationId) -> windows_core::Result<()>;
    fn CommitButtonText(&self) -> windows_core::Result<windows_core::HSTRING>;
    fn SetCommitButtonText(&self, value: &windows_core::HSTRING) -> windows_core::Result<()>;
    fn FileTypeChoices(
        &self,
    ) -> windows_core::Result<
        windows_collections::IMap<
            windows_core::HSTRING,
            windows_collections::IVector<windows_core::HSTRING>,
        >,
    >;
    fn DefaultFileExtension(&self) -> windows_core::Result<windows_core::HSTRING>;
    fn SetDefaultFileExtension(&self, value: &windows_core::HSTRING) -> windows_core::Result<()>;
    fn SuggestedFileName(&self) -> windows_core::Result<windows_core::HSTRING>;
    fn SetSuggestedFileName(&self, value: &windows_core::HSTRING) -> windows_core::Result<()>;
    fn SuggestedFolder(&self) -> windows_core::Result<windows_core::HSTRING>;
    fn SetSuggestedFolder(&self, value: &windows_core::HSTRING) -> windows_core::Result<()>;
    fn PickSaveFileAsync(
        &self,
    ) -> windows_core::Result<windows_future::IAsyncOperation<PickFileResult>>;
}
impl IFileSavePicker_Vtbl {
    pub const fn new<Identity: IFileSavePicker_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn SuggestedStartLocation<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut PickerLocationId,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileSavePicker_Impl::SuggestedStartLocation(this) {
                    Ok(ok__) => {
                        result__.write(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn SetSuggestedStartLocation<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            value: PickerLocationId,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IFileSavePicker_Impl::SetSuggestedStartLocation(this, value).into()
            }
        }
        unsafe extern "system" fn CommitButtonText<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileSavePicker_Impl::CommitButtonText(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn SetCommitButtonText<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            value: *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IFileSavePicker_Impl::SetCommitButtonText(this, core::mem::transmute(&value)).into()
            }
        }
        unsafe extern "system" fn FileTypeChoices<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileSavePicker_Impl::FileTypeChoices(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn DefaultFileExtension<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileSavePicker_Impl::DefaultFileExtension(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn SetDefaultFileExtension<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            value: *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IFileSavePicker_Impl::SetDefaultFileExtension(this, core::mem::transmute(&value))
                    .into()
            }
        }
        unsafe extern "system" fn SuggestedFileName<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileSavePicker_Impl::SuggestedFileName(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn SetSuggestedFileName<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            value: *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IFileSavePicker_Impl::SetSuggestedFileName(this, core::mem::transmute(&value))
                    .into()
            }
        }
        unsafe extern "system" fn SuggestedFolder<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileSavePicker_Impl::SuggestedFolder(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn SetSuggestedFolder<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            value: *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IFileSavePicker_Impl::SetSuggestedFolder(this, core::mem::transmute(&value)).into()
            }
        }
        unsafe extern "system" fn PickSaveFileAsync<
            Identity: IFileSavePicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileSavePicker_Impl::PickSaveFileAsync(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<Identity, IFileSavePicker, OFFSET>(),
            SuggestedStartLocation: SuggestedStartLocation::<Identity, OFFSET>,
            SetSuggestedStartLocation: SetSuggestedStartLocation::<Identity, OFFSET>,
            CommitButtonText: CommitButtonText::<Identity, OFFSET>,
            SetCommitButtonText: SetCommitButtonText::<Identity, OFFSET>,
            FileTypeChoices: FileTypeChoices::<Identity, OFFSET>,
            DefaultFileExtension: DefaultFileExtension::<Identity, OFFSET>,
            SetDefaultFileExtension: SetDefaultFileExtension::<Identity, OFFSET>,
            SuggestedFileName: SuggestedFileName::<Identity, OFFSET>,
            SetSuggestedFileName: SetSuggestedFileName::<Identity, OFFSET>,
            SuggestedFolder: SuggestedFolder::<Identity, OFFSET>,
            SetSuggestedFolder: SetSuggestedFolder::<Identity, OFFSET>,
            PickSaveFileAsync: PickSaveFileAsync::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IFileSavePicker as windows_core::Interface>::IID
    }
}
#[repr(C)]
pub struct IFileSavePicker_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub SuggestedStartLocation: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut PickerLocationId,
    ) -> windows_core::HRESULT,
    pub SetSuggestedStartLocation: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        PickerLocationId,
    ) -> windows_core::HRESULT,
    pub CommitButtonText: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SetCommitButtonText: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub FileTypeChoices: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub DefaultFileExtension: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SetDefaultFileExtension: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SuggestedFileName: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SetSuggestedFileName: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SuggestedFolder: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SetSuggestedFolder: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub PickSaveFileAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IFileSavePickerFactory,
    IFileSavePickerFactory_Vtbl,
    0x2e256696_30b6_5a05_a8f5_c752db6dd268
);
impl windows_core::RuntimeType for IFileSavePickerFactory {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
    const NAME: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"Microsoft.Windows.Storage.Pickers.IFileSavePickerFactory",
    );
}
impl windows_core::RuntimeName for IFileSavePickerFactory {
    const NAME: &'static str = "Microsoft.Windows.Storage.Pickers.IFileSavePickerFactory";
}
pub trait IFileSavePickerFactory_Impl: windows_core::IUnknownImpl {
    fn CreateInstance(&self, windowId: &WindowId) -> windows_core::Result<FileSavePicker>;
}
impl IFileSavePickerFactory_Vtbl {
    pub const fn new<Identity: IFileSavePickerFactory_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn CreateInstance<
            Identity: IFileSavePickerFactory_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            windowid: WindowId,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFileSavePickerFactory_Impl::CreateInstance(
                    this,
                    core::mem::transmute(&windowid),
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<Identity, IFileSavePickerFactory, OFFSET>(
            ),
            CreateInstance: CreateInstance::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IFileSavePickerFactory as windows_core::Interface>::IID
    }
}
#[repr(C)]
pub struct IFileSavePickerFactory_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub CreateInstance: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        WindowId,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IFolderPicker,
    IFolderPicker_Vtbl,
    0x3ef0d1ca_97c6_5873_8ea2_02c450174290
);
impl windows_core::RuntimeType for IFolderPicker {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
    const NAME: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"Microsoft.Windows.Storage.Pickers.IFolderPicker",
    );
}
impl windows_core::RuntimeName for IFolderPicker {
    const NAME: &'static str = "Microsoft.Windows.Storage.Pickers.IFolderPicker";
}
pub trait IFolderPicker_Impl: windows_core::IUnknownImpl {
    fn ViewMode(&self) -> windows_core::Result<PickerViewMode>;
    fn SetViewMode(&self, value: PickerViewMode) -> windows_core::Result<()>;
    fn SuggestedStartLocation(&self) -> windows_core::Result<PickerLocationId>;
    fn SetSuggestedStartLocation(&self, value: PickerLocationId) -> windows_core::Result<()>;
    fn CommitButtonText(&self) -> windows_core::Result<windows_core::HSTRING>;
    fn SetCommitButtonText(&self, value: &windows_core::HSTRING) -> windows_core::Result<()>;
    fn PickSingleFolderAsync(
        &self,
    ) -> windows_core::Result<windows_future::IAsyncOperation<PickFolderResult>>;
}
impl IFolderPicker_Vtbl {
    pub const fn new<Identity: IFolderPicker_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn ViewMode<Identity: IFolderPicker_Impl, const OFFSET: isize>(
            this: *mut core::ffi::c_void,
            result__: *mut PickerViewMode,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFolderPicker_Impl::ViewMode(this) {
                    Ok(ok__) => {
                        result__.write(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn SetViewMode<Identity: IFolderPicker_Impl, const OFFSET: isize>(
            this: *mut core::ffi::c_void,
            value: PickerViewMode,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IFolderPicker_Impl::SetViewMode(this, value).into()
            }
        }
        unsafe extern "system" fn SuggestedStartLocation<
            Identity: IFolderPicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut PickerLocationId,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFolderPicker_Impl::SuggestedStartLocation(this) {
                    Ok(ok__) => {
                        result__.write(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn SetSuggestedStartLocation<
            Identity: IFolderPicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            value: PickerLocationId,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IFolderPicker_Impl::SetSuggestedStartLocation(this, value).into()
            }
        }
        unsafe extern "system" fn CommitButtonText<
            Identity: IFolderPicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFolderPicker_Impl::CommitButtonText(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn SetCommitButtonText<
            Identity: IFolderPicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            value: *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                IFolderPicker_Impl::SetCommitButtonText(this, core::mem::transmute(&value)).into()
            }
        }
        unsafe extern "system" fn PickSingleFolderAsync<
            Identity: IFolderPicker_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFolderPicker_Impl::PickSingleFolderAsync(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<Identity, IFolderPicker, OFFSET>(),
            ViewMode: ViewMode::<Identity, OFFSET>,
            SetViewMode: SetViewMode::<Identity, OFFSET>,
            SuggestedStartLocation: SuggestedStartLocation::<Identity, OFFSET>,
            SetSuggestedStartLocation: SetSuggestedStartLocation::<Identity, OFFSET>,
            CommitButtonText: CommitButtonText::<Identity, OFFSET>,
            SetCommitButtonText: SetCommitButtonText::<Identity, OFFSET>,
            PickSingleFolderAsync: PickSingleFolderAsync::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IFolderPicker as windows_core::Interface>::IID
    }
}
#[repr(C)]
pub struct IFolderPicker_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub ViewMode: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut PickerViewMode,
    ) -> windows_core::HRESULT,
    pub SetViewMode:
        unsafe extern "system" fn(*mut core::ffi::c_void, PickerViewMode) -> windows_core::HRESULT,
    pub SuggestedStartLocation: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut PickerLocationId,
    ) -> windows_core::HRESULT,
    pub SetSuggestedStartLocation: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        PickerLocationId,
    ) -> windows_core::HRESULT,
    pub CommitButtonText: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub SetCommitButtonText: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
    pub PickSingleFolderAsync: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IFolderPickerFactory,
    IFolderPickerFactory_Vtbl,
    0xe1550d89_b389_5886_8395_022b1588d6a8
);
impl windows_core::RuntimeType for IFolderPickerFactory {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
    const NAME: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"Microsoft.Windows.Storage.Pickers.IFolderPickerFactory",
    );
}
impl windows_core::RuntimeName for IFolderPickerFactory {
    const NAME: &'static str = "Microsoft.Windows.Storage.Pickers.IFolderPickerFactory";
}
pub trait IFolderPickerFactory_Impl: windows_core::IUnknownImpl {
    fn CreateInstance(&self, windowId: &WindowId) -> windows_core::Result<FolderPicker>;
}
impl IFolderPickerFactory_Vtbl {
    pub const fn new<Identity: IFolderPickerFactory_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn CreateInstance<
            Identity: IFolderPickerFactory_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            windowid: WindowId,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IFolderPickerFactory_Impl::CreateInstance(
                    this,
                    core::mem::transmute(&windowid),
                ) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<Identity, IFolderPickerFactory, OFFSET>(
            ),
            CreateInstance: CreateInstance::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IFolderPickerFactory as windows_core::Interface>::IID
    }
}
#[repr(C)]
pub struct IFolderPickerFactory_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub CreateInstance: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        WindowId,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IPickFileResult,
    IPickFileResult_Vtbl,
    0xe6f2e3d6_7bb0_5d81_9e7d_6fd35a1f25ab
);
impl windows_core::RuntimeType for IPickFileResult {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
    const NAME: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"Microsoft.Windows.Storage.Pickers.IPickFileResult",
    );
}
impl windows_core::RuntimeName for IPickFileResult {
    const NAME: &'static str = "Microsoft.Windows.Storage.Pickers.IPickFileResult";
}
pub trait IPickFileResult_Impl: windows_core::IUnknownImpl {
    fn Path(&self) -> windows_core::Result<windows_core::HSTRING>;
}
impl IPickFileResult_Vtbl {
    pub const fn new<Identity: IPickFileResult_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn Path<Identity: IPickFileResult_Impl, const OFFSET: isize>(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IPickFileResult_Impl::Path(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<Identity, IPickFileResult, OFFSET>(),
            Path: Path::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IPickFileResult as windows_core::Interface>::IID
    }
}
#[repr(C)]
pub struct IPickFileResult_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub Path: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
windows_core::imp::define_interface!(
    IPickFolderResult,
    IPickFolderResult_Vtbl,
    0x6f7fd316_fe29_59d1_9343_c49cf5cde680
);
impl windows_core::RuntimeType for IPickFolderResult {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
    const NAME: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"Microsoft.Windows.Storage.Pickers.IPickFolderResult",
    );
}
impl windows_core::RuntimeName for IPickFolderResult {
    const NAME: &'static str = "Microsoft.Windows.Storage.Pickers.IPickFolderResult";
}
pub trait IPickFolderResult_Impl: windows_core::IUnknownImpl {
    fn Path(&self) -> windows_core::Result<windows_core::HSTRING>;
}
impl IPickFolderResult_Vtbl {
    pub const fn new<Identity: IPickFolderResult_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn Path<Identity: IPickFolderResult_Impl, const OFFSET: isize>(
            this: *mut core::ffi::c_void,
            result__: *mut *mut core::ffi::c_void,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IPickFolderResult_Impl::Path(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        core::mem::forget(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<Identity, IPickFolderResult, OFFSET>(),
            Path: Path::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IPickFolderResult as windows_core::Interface>::IID
    }
}
#[repr(C)]
pub struct IPickFolderResult_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub Path: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        *mut *mut core::ffi::c_void,
    ) -> windows_core::HRESULT,
}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PickFileResult(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    PickFileResult,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl PickFileResult {
    pub fn Path(&self) -> windows_core::Result<windows_core::HSTRING> {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).Path)(
                windows_core::Interface::as_raw(self),
                &mut result__,
            )
            .map(|| core::mem::transmute(result__))
        }
    }
}
impl windows_core::RuntimeType for PickFileResult {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IPickFileResult>();
}
unsafe impl windows_core::Interface for PickFileResult {
    type Vtable = <IPickFileResult as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IPickFileResult as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for PickFileResult {
    const NAME: &'static str = "Microsoft.Windows.Storage.Pickers.PickFileResult";
}
unsafe impl Send for PickFileResult {}
unsafe impl Sync for PickFileResult {}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PickFolderResult(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    PickFolderResult,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl PickFolderResult {
    pub fn Path(&self) -> windows_core::Result<windows_core::HSTRING> {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).Path)(
                windows_core::Interface::as_raw(self),
                &mut result__,
            )
            .map(|| core::mem::transmute(result__))
        }
    }
}
impl windows_core::RuntimeType for PickFolderResult {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IPickFolderResult>();
}
unsafe impl windows_core::Interface for PickFolderResult {
    type Vtable = <IPickFolderResult as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IPickFolderResult as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for PickFolderResult {
    const NAME: &'static str = "Microsoft.Windows.Storage.Pickers.PickFolderResult";
}
unsafe impl Send for PickFolderResult {}
unsafe impl Sync for PickFolderResult {}
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct PickerLocationId(pub i32);
impl PickerLocationId {
    pub const DocumentsLibrary: Self = Self(0);
    pub const ComputerFolder: Self = Self(1);
    pub const Desktop: Self = Self(2);
    pub const Downloads: Self = Self(3);
    pub const MusicLibrary: Self = Self(5);
    pub const PicturesLibrary: Self = Self(6);
    pub const VideosLibrary: Self = Self(7);
    pub const Objects3D: Self = Self(8);
    pub const Unspecified: Self = Self(9);
}
impl windows_core::TypeKind for PickerLocationId {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for PickerLocationId {
    const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"enum(Microsoft.Windows.Storage.Pickers.PickerLocationId;i4)",
    );
    const NAME: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"Microsoft.Windows.Storage.Pickers.PickerLocationId",
    );
}
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct PickerViewMode(pub i32);
impl PickerViewMode {
    pub const List: Self = Self(0);
    pub const Thumbnail: Self = Self(1);
}
impl windows_core::TypeKind for PickerViewMode {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for PickerViewMode {
    const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"enum(Microsoft.Windows.Storage.Pickers.PickerViewMode;i4)",
    );
    const NAME: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"Microsoft.Windows.Storage.Pickers.PickerViewMode",
    );
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct WindowId {
    pub Value: u64,
}
impl windows_core::TypeKind for WindowId {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for WindowId {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::from_slice(b"struct(Microsoft.UI.WindowId;u8)");
    const NAME: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::from_slice(b"Microsoft.UI.WindowId");
}
